import type { AIFunctionConfig } from './aiRegistry';

/**
 * Données du registre des fonctions IA — extrait de aiRegistry.ts pour réduire la taille du fichier.
 * Ne pas modifier les types ici : ils sont définis dans aiRegistry.ts.
 */
export const AI_FUNCTIONS_REGISTRY: AIFunctionConfig[] = [
  // ==================== EMAIL ====================
  {
    id: 'process-email-with-ai',
    label: 'Classification Email',
    description: 'Classifie les emails, extrait contacts, tags et catégories automatiquement.',
    category: 'email',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un assistant IA spécialisé dans l'analyse et la classification d'emails professionnels...",
    processingType: 'extraction',
    securityFeatures: ['sanitizeForAI', 'wrapUserContent'],
  },
  {
    id: 'correct-spelling-email',
    label: 'Correction orthographique',
    description: 'Corrige l\'orthographe et la grammaire des emails sans modifier le fond.',
    category: 'email',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 4000,
      response_format: 'text',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un correcteur professionnel. Réponds uniquement avec le texte corrigé, sans commentaire.",
    processingType: 'email_spelling',
    securityFeatures: ['sanitizeForAI', 'wrapUserContent'],
  },
  {
    id: 'reformulate-email',
    label: 'Reformulation',
    description: 'Reformule les emails selon un style choisi (professionnel, concis, convivial).',
    category: 'email',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'text',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un assistant de reformulation professionnel. Réponds uniquement avec le texte reformulé...",
    processingType: 'email_reformulate',
    securityFeatures: ['sanitizeForAI', 'wrapUserContent', 'detectPromptInjection'],
  },
  {
    id: 'translate-email',
    label: 'Traduction Email',
    description: 'Traduit les emails en français, anglais, espagnol, allemand, italien ou portugais.',
    category: 'email',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'text',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un traducteur professionnel. Réponds uniquement avec la traduction, sans commentaire.",
    processingType: 'email_translate',
    securityFeatures: ['sanitizeForAI', 'wrapUserContent', 'detectPromptInjection'],
  },
  {
    id: 'suggest-email-content',
    label: 'Suggestion de contenu',
    description: 'Génère des suggestions de réponse pour les emails entrants.',
    category: 'email',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 1000,
      response_format: 'text',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un assistant de rédaction email professionnel. Suggère une réponse adaptée...",
    processingType: 'email_suggestion',
    securityFeatures: ['sanitizeForAI', 'wrapUserContent'],
  },
  {
    id: 'generate-thread-title',
    label: 'Titre de thread',
    description: 'Génère un titre court et lisible pour les fils de conversation email.',
    category: 'email',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 100,
      response_format: 'text',
      timeout_ms: 30000,
    },
    systemPromptPreview: "Génère un titre court (max 60 caractères) pour ce fil de discussion email...",
    processingType: 'email_title_generation',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'detect-and-translate-email',
    label: 'Détection & Traduction',
    description: 'Détecte la langue d\'un email et le traduit automatiquement en français.',
    category: 'email',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Détecte la langue du texte et traduis-le en français si nécessaire...",
    processingType: 'email_translate',
    securityFeatures: ['sanitizeForAI', 'wrapUserContent'],
  },
  {
    id: 'generate-thread-summary',
    label: 'Résumé de thread',
    description: 'Génère un résumé concis d\'un fil de discussion email pour les événements calendrier.',
    category: 'email',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 500,
      response_format: 'text',
      timeout_ms: 60000,
    },
    systemPromptPreview: "Résume ce fil de discussion email en 2-3 phrases concises...",
    processingType: 'email_summary',
    securityFeatures: ['sanitizeForAI'],
  },

  // ==================== CRM ====================
  {
    id: 'generate-ai-suggestions',
    label: 'Suggestions IA',
    description: 'Génère des suggestions d\'actions CRM basées sur l\'analyse des emails et données client.',
    category: 'crm',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un assistant CRM expert. Analyse les données et suggère des actions pertinentes...",
    processingType: 'suggestion_generation',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'analyze-rapports-insights',
    label: 'Analyse rapports',
    description: 'Analyse les tendances et anomalies dans les rapports CRM.',
    category: 'crm',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un analyste de données expert. Analyse les tendances, détecte les anomalies...",
    processingType: 'rapports_insights',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'chat-data-query',
    label: 'Requête données',
    description: 'Interprète des questions en langage naturel pour interroger la base de données CRM.',
    category: 'crm',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un assistant data qui traduit des questions en requêtes structurées...",
    processingType: 'data_query',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'smart-tasks-from-content',
    label: 'Tâches intelligentes',
    description: 'Extrait et crée des tâches structurées depuis le contenu des emails ou Pulse.',
    category: 'crm',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Analyse le contenu et extrait les tâches à réaliser avec priorité et assignation...",
    processingType: 'smart_tasks',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'daily-ai-insights-analysis',
    label: 'Analyse quotidienne',
    description: 'Analyse automatique quotidienne des données pour détecter insights et alertes.',
    category: 'crm',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Analyse les données du jour pour détecter tendances, anomalies et opportunités...",
    processingType: 'daily_insights',
    securityFeatures: [],
  },
  {
    id: 'analyze-medical-economic-study',
    label: 'Étude médico-économique',
    description: 'Analyse approfondie d\'études médico-économiques avec GPT-5.4.',
    category: 'crm',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2'],
    parameters: {
      reasoning_effort: 'high',
      verbosity: 'high',
      max_completion_tokens: 4000,
      response_format: 'json_object',
      timeout_ms: 120000,
    },
    systemPromptPreview: "Tu es un expert en analyses médico-économiques. Analyse cette étude en profondeur...",
    processingType: 'medical_economic_study_analysis',
    securityFeatures: ['sanitizeForAI'],
  },

  // ==================== RH ====================
  {
    id: 'parse-bulletin-salaire',
    label: 'Parsing bulletin de paie',
    description: 'Extrait les données structurées des bulletins de salaire PDF via GPT-5.4.',
    category: 'rh',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un expert en traitement de bulletins de paie. Extrait les données structurées...",
    processingType: 'rh_bulletin_parsing',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'parse-bulletin-temp',
    label: 'Parsing bulletin (batch)',
    description: 'Version batch du parsing de bulletins pour l\'import en masse.',
    category: 'rh',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Extraction structurée de données depuis un bulletin de paie numérisé...",
    processingType: 'rh_bulletin_parsing',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'check-absence-conflicts',
    label: 'Conflits absences',
    description: 'Détecte les conflits potentiels dans les plannings d\'absences.',
    category: 'rh',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'json_object',
      timeout_ms: 60000,
    },
    systemPromptPreview: "Analyse les dates d'absence et détecte les conflits de planning...",
    processingType: 'absence_conflict_check',
    securityFeatures: [],
  },
  {
    id: 'suggest-employee-training',
    label: 'Suggestions formation',
    description: 'Suggère des formations adaptées aux collaborateurs basées sur leurs compétences.',
    category: 'rh',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 2000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Analyse le profil de l'employé et recommande des formations pertinentes...",
    processingType: 'training_suggestion',
    securityFeatures: [],
  },
  {
    id: 'prepare-annual-review',
    label: 'Bilan annuel',
    description: 'Prépare les éléments du bilan annuel d\'un collaborateur.',
    category: 'rh',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2'],
    parameters: {
      reasoning_effort: 'high',
      verbosity: 'high',
      max_completion_tokens: 4000,
      response_format: 'json_object',
      timeout_ms: 120000,
    },
    systemPromptPreview: "Prépare un bilan annuel complet pour ce collaborateur en analysant ses données...",
    processingType: 'annual_review',
    securityFeatures: [],
  },
  {
    id: 'analyze-rh-insights',
    label: 'Insights RH',
    description: 'Analyse des données RH pour détecter tendances et recommandations.',
    category: 'rh',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Analyse les données RH et génère des insights sur la masse salariale, les absences...",
    processingType: 'rh_insights',
    securityFeatures: [],
  },
  {
    id: 'parse-cv-with-ai',
    label: 'Parsing CV',
    description: 'Extrait les données structurées d\'un CV (expériences, compétences, formations).',
    category: 'rh',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'low',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Extrait les informations structurées de ce CV : identité, expériences, compétences...",
    processingType: 'cv_parsing',
    securityFeatures: ['sanitizeForAI'],
  },

  // ==================== R&D ====================
  {
    id: 'rd-ai-assist',
    label: 'R&D Assistance',
    description: 'Aide à la rédaction de user stories, critères d\'acceptation et tâches.',
    category: 'rd',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un expert en méthodologie agile. Aide à rédiger des user stories avec critères...",
    processingType: 'rd_assist',
    securityFeatures: ['sanitizeForAI'],
  },

  // ==================== JARVIS ====================
  {
    id: 'jarvis-brain',
    label: 'Jarvis Chat',
    description: 'Moteur principal de Jarvis - GPT-5.4 avec tool calling et fallback GPT-5.2.',
    category: 'jarvis',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 4000,
      response_format: 'text',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es Jarvis, un assistant IA omniscient intégré à OpenPulse. Tu as accès à 100+ outils...",
    processingType: 'jarvis-chat',
    securityFeatures: ['sanitizeForAI', 'toolCallValidation'],
  },
  {
    id: 'jarvis-brain-stream',
    label: 'Jarvis Chat (Stream)',
    description: 'Version streaming SSE du moteur Jarvis pour réponses en temps réel.',
    category: 'jarvis',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 4000,
      response_format: 'text',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es Jarvis, assistant IA streaming. Réponds en temps réel avec tool calling...",
    processingType: 'jarvis-chat',
    securityFeatures: ['sanitizeForAI', 'toolCallValidation'],
  },
  {
    id: 'jarvis-vision',
    label: 'Jarvis Vision',
    description: 'Analyse d\'images et captures d\'écran via GPT-5 Vision.',
    category: 'jarvis',
    model: 'gpt-5-vision',
    fallbackChain: ['gpt-5-vision'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'text',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Analyse cette image et décris ce que tu vois. Extrais les données pertinentes...",
    processingType: 'jarvis-vision-screenshot',
    securityFeatures: [],
  },
  {
    id: 'jarvis-proactive-scan',
    label: 'Jarvis Scan proactif',
    description: 'Scan automatique toutes les 5 min pour détecter alertes et anomalies.',
    category: 'jarvis',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'json_object',
      timeout_ms: 60000,
    },
    systemPromptPreview: "Analyse les données récentes et détecte les alertes, anomalies et opportunités...",
    processingType: 'jarvis_proactive',
    securityFeatures: [],
  },
  {
    id: 'jarvis-daily-briefing',
    label: 'Jarvis Briefing',
    description: 'Génère le briefing quotidien personnalisé pour chaque utilisateur.',
    category: 'jarvis',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Génère un briefing matinal personnalisé avec les priorités, alertes et actions...",
    processingType: 'jarvis_briefing',
    securityFeatures: [],
  },

  // ==================== PULSE ====================
  {
    id: 'pulse-ai-summarize',
    label: 'Pulse Résumé',
    description: 'Résume les articles Pulse et les notes de réunion.',
    category: 'pulse',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 3000,
      response_format: 'text',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Résume cet article de manière concise en conservant les points clés...",
    processingType: 'pulse_summarize',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'pulse-ai-editor',
    label: 'Pulse Éditeur',
    description: 'Assistant d\'édition pour améliorer les articles Pulse.',
    category: 'pulse',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'text',
      timeout_ms: 60000,
    },
    systemPromptPreview: "Améliore ce texte en gardant le style et le ton de l'auteur...",
    processingType: 'pulse_editor',
    securityFeatures: ['sanitizeForAI'],
  },

  // ==================== TRESORERIE ====================
  {
    id: 'smart-reconcile-qonto',
    label: 'Réconciliation Qonto',
    description: 'Réconciliation intelligente entre transactions Qonto et revenus/dépenses.',
    category: 'tresorerie',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Analyse les transactions bancaires et associe-les aux factures et dépenses...",
    processingType: 'qonto_reconciliation',
    securityFeatures: [],
  },
  {
    id: 'predict-cashflow',
    label: 'Prévision trésorerie',
    description: 'Prédit les flux de trésorerie futurs basés sur l\'historique.',
    category: 'tresorerie',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2'],
    parameters: {
      reasoning_effort: 'high',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 120000,
    },
    systemPromptPreview: "Analyse l'historique de trésorerie et prédis les flux futurs sur 3 mois...",
    processingType: 'cashflow_prediction',
    securityFeatures: [],
  },
  {
    id: 'analyze-tresorerie-insights',
    label: 'Insights trésorerie',
    description: 'Analyse des données de trésorerie pour détecter tendances et alertes.',
    category: 'tresorerie',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Analyse les données financières et génère des insights sur la trésorerie...",
    processingType: 'tresorerie_insights',
    securityFeatures: [],
  },
  {
    id: 'send-invoice-reminders',
    label: 'Relances factures',
    description: 'Génère et envoie des relances automatiques pour factures impayées.',
    category: 'tresorerie',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 1000,
      response_format: 'text',
      timeout_ms: 60000,
    },
    systemPromptPreview: "Rédige un email de relance professionnel pour une facture impayée...",
    processingType: 'invoice_reminder',
    securityFeatures: [],
  },

  // ==================== CALENDRIER ====================
  {
    id: 'detect-calendar-invitations',
    label: 'Détection invitations',
    description: 'Détecte les invitations calendrier dans les emails (fichiers ICS).',
    category: 'calendrier',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 500,
      response_format: 'json_object',
      timeout_ms: 30000,
    },
    systemPromptPreview: "Analyse cet email et détecte s'il contient une invitation calendrier...",
    processingType: 'calendar_detection',
    securityFeatures: [],
  },
  {
    id: 'calendar-ai-create',
    label: 'Création événement IA',
    description: 'Crée des événements calendrier à partir de commandes en langage naturel.',
    category: 'calendrier',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 1000,
      response_format: 'json_object',
      timeout_ms: 60000,
    },
    systemPromptPreview: "Interprète cette demande en langage naturel et crée un événement calendrier...",
    processingType: 'calendar_ai_create',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'generate-visio-summary',
    label: 'Résumé visio',
    description: 'Génère un résumé structuré d\'une réunion visio à partir de la transcription.',
    category: 'calendrier',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Résume cette transcription de réunion en extrayant les points clés, décisions...",
    processingType: 'visio_summary',
    securityFeatures: [],
  },

  // ==================== AUDIO ====================
  {
    id: 'transcribe-audio',
    label: 'Transcription audio',
    description: 'Transcrit l\'audio en texte via Azure Whisper.',
    category: 'autre',
    model: 'whisper-1',
    fallbackChain: ['whisper-1'],
    parameters: {
      reasoning_effort: 'N/A',
      verbosity: 'N/A',
      max_completion_tokens: 0,
      timeout_ms: 120000,
    },
    systemPromptPreview: 'N/A - Modèle de transcription audio',
    processingType: 'audio_transcription',
    securityFeatures: [],
  },
  {
    id: 'azure-transcribe-audio',
    label: 'Transcription visio',
    description: 'Transcription audio en temps réel pour les réunions visio.',
    category: 'autre',
    model: 'whisper-1',
    fallbackChain: ['whisper-1'],
    parameters: {
      reasoning_effort: 'N/A',
      verbosity: 'N/A',
      max_completion_tokens: 0,
      timeout_ms: 120000,
    },
    systemPromptPreview: 'N/A - Transcription audio Azure Speech-to-Text',
    processingType: 'audio_transcription',
    securityFeatures: [],
  },

  // ==================== SUPPORT ====================
  {
    id: 'live-chat-ai-respond',
    label: 'Live Chat IA',
    description: 'Répond automatiquement aux messages du chat support via IA.',
    category: 'support',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 1000,
      response_format: 'text',
      timeout_ms: 60000,
    },
    systemPromptPreview: "Tu es l'assistant support de OpenPulse. Réponds aux questions des utilisateurs...",
    processingType: 'live_chat_response',
    securityFeatures: ['sanitizeForAI'],
  },

  // ==================== AUTRE ====================
  {
    id: 'analyze-simulator-data',
    label: 'Analyse simulateur',
    description: 'Analyse les données issues du simulateur médico-économique.',
    category: 'autre',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Analyse ces données de simulation et génère des insights pertinents...",
    processingType: 'simulator_data_analysis',
    securityFeatures: [],
  },
  {
    id: 'contract-ai-assist',
    label: 'Contrats IA',
    description: 'Assistance IA pour la rédaction et analyse de contrats.',
    category: 'autre',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'],
    parameters: {
      reasoning_effort: 'medium',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'text',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Tu es un assistant juridique expert. Aide à rédiger et analyser les contrats...",
    processingType: 'contract_assist',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'structure-note',
    label: 'Structuration notes',
    description: 'Structure et organise des notes brutes en format professionnel.',
    category: 'autre',
    model: 'gpt-5-mini',
    fallbackChain: ['gpt-5-mini', 'gpt-5.4'],
    parameters: {
      reasoning_effort: 'low',
      verbosity: 'low',
      max_completion_tokens: 2000,
      response_format: 'text',
      timeout_ms: 60000,
    },
    systemPromptPreview: "Organise ces notes brutes en un document structuré avec titres et sections...",
    processingType: 'note_structuring',
    securityFeatures: ['sanitizeForAI'],
  },
  {
    id: 'generate-direction-alerts',
    label: 'Alertes direction',
    description: 'Génère des alertes stratégiques pour la direction basées sur les données.',
    category: 'autre',
    model: 'gpt-5.4',
    fallbackChain: ['gpt-5.4', 'gpt-5.2'],
    parameters: {
      reasoning_effort: 'high',
      verbosity: 'medium',
      max_completion_tokens: 3000,
      response_format: 'json_object',
      timeout_ms: 90000,
    },
    systemPromptPreview: "Analyse les données de l'entreprise et génère des alertes stratégiques pour la direction...",
    processingType: 'direction_alerts',
    securityFeatures: [],
  },
];
