import { useState, useMemo } from 'react'
import { Input } from '@/components/ui/input'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { cn } from '@/lib/utils'

interface ReactionPickerProps {
  onSelect: (emoji: string) => void
}

const EMOJI_CATEGORIES = {
  recent: {
    label: '🕐',
    emojis: ['👍', '❤️', '😄', '🎉', '🤔', '👀', '🔥', '💯', '✅', '🙏', '👏', '😍'],
  },
  smileys: {
    label: '😀',
    emojis: [
      '😀',
      '😃',
      '😄',
      '😁',
      '😅',
      '😂',
      '🤣',
      '😊',
      '😇',
      '🙂',
      '🙃',
      '😉',
      '😌',
      '😍',
      '🥰',
      '😘',
      '😗',
      '😙',
      '😚',
      '😋',
      '😛',
      '😜',
      '🤪',
      '😝',
      '🤑',
      '🤗',
      '🤭',
      '🤫',
      '🤔',
      '🤐',
      '🤨',
      '😐',
      '😑',
      '😶',
      '😏',
      '😒',
      '🙄',
      '😬',
      '🤥',
      '😔',
      '😪',
      '🤤',
      '😴',
      '😷',
      '🤒',
      '🤕',
      '🤢',
      '🤮',
      '🥵',
      '🥶',
      '😵',
      '🤯',
      '🥳',
      '🥸',
      '😎',
      '🤓',
      '🧐',
      '😕',
      '😟',
      '🙁',
      '☹️',
      '😮',
      '😯',
      '😲',
      '😳',
      '🥺',
      '😦',
      '😧',
      '😨',
      '😰',
      '😥',
      '😢',
      '😭',
      '😱',
      '😖',
      '😣',
      '😞',
      '😓',
      '😩',
      '😫',
      '🥱',
      '😤',
      '😡',
      '😠',
      '🤬',
      '😈',
      '👿',
      '💀',
    ],
  },
  gestures: {
    label: '👋',
    emojis: [
      '👋',
      '🤚',
      '🖐️',
      '✋',
      '🖖',
      '👌',
      '🤌',
      '🤏',
      '✌️',
      '🤞',
      '🫰',
      '🤟',
      '🤘',
      '🤙',
      '👈',
      '👉',
      '👆',
      '🖕',
      '👇',
      '☝️',
      '👍',
      '👎',
      '✊',
      '👊',
      '🤛',
      '🤜',
      '👏',
      '🙌',
      '🫶',
      '👐',
      '🤲',
      '🤝',
      '🙏',
      '✍️',
      '💅',
      '🤳',
      '💪',
      '🦾',
      '🦿',
      '🦵',
      '🦶',
      '👂',
      '🦻',
      '👃',
      '🧠',
      '🫀',
      '🫁',
      '🦷',
      '🦴',
      '👀',
      '👁️',
      '👅',
      '👄',
      '💋',
    ],
  },
  people: {
    label: '👤',
    emojis: [
      '👶',
      '🧒',
      '👦',
      '👧',
      '🧑',
      '👱',
      '👨',
      '🧔',
      '👩',
      '🧓',
      '👴',
      '👵',
      '🙍',
      '🙎',
      '🙅',
      '🙆',
      '💁',
      '🙋',
      '🧏',
      '🙇',
      '🤦',
      '🤷',
      '👮',
      '🕵️',
      '💂',
      '👷',
      '🤴',
      '👸',
      '👳',
      '👲',
      '🧕',
      '🤵',
      '👰',
      '🤱',
      '🦸',
      '🦹',
      '🧙',
      '🧚',
      '🧛',
      '🧜',
      '🧝',
      '🧞',
      '🧟',
      '💆',
      '💇',
      '🚶',
      '🧍',
      '🧎',
      '🏃',
      '💃',
      '🕺',
      '👯',
      '🧑‍🤝‍🧑',
      '👫',
      '👨‍👩‍👦',
      '👪',
    ],
  },
  hearts: {
    label: '❤️',
    emojis: [
      '❤️',
      '🧡',
      '💛',
      '💚',
      '💙',
      '💜',
      '🖤',
      '🤍',
      '🤎',
      '💔',
      '❣️',
      '💕',
      '💞',
      '💓',
      '💗',
      '💖',
      '💘',
      '💝',
      '💟',
      '♥️',
      '🫶',
      '💌',
      '💋',
      '💏',
      '💑',
      '❤️‍🔥',
      '❤️‍🩹',
    ],
  },
  animals: {
    label: '🐶',
    emojis: [
      '🐶',
      '🐱',
      '🐭',
      '🐹',
      '🐰',
      '🦊',
      '🐻',
      '🐼',
      '🐨',
      '🐯',
      '🦁',
      '🐮',
      '🐷',
      '🐽',
      '🐸',
      '🐵',
      '🙈',
      '🙉',
      '🙊',
      '🐒',
      '🐔',
      '🐧',
      '🐦',
      '🐤',
      '🐣',
      '🦆',
      '🦅',
      '🦉',
      '🦇',
      '🐺',
      '🐗',
      '🐴',
      '🦄',
      '🐝',
      '🪲',
      '🐛',
      '🦋',
      '🐌',
      '🐞',
      '🐜',
      '🦟',
      '🕷️',
      '🕸️',
      '🦂',
      '🐢',
      '🐍',
      '🦎',
      '🦖',
      '🐙',
      '🦑',
      '🦐',
      '🦞',
      '🦀',
      '🐡',
      '🐠',
      '🐟',
      '🐬',
      '🐳',
      '🐋',
      '🦈',
      '🐊',
      '🐅',
      '🐆',
      '🦓',
      '🦍',
      '🦧',
      '🐘',
      '🦛',
      '🦏',
      '🐪',
      '🐫',
      '🦒',
      '🐃',
      '🐂',
      '🐄',
      '🐎',
      '🐖',
      '🐏',
      '🐑',
      '🦙',
      '🐐',
      '🦌',
      '🐕',
      '🐩',
      '🐈',
      '🐓',
      '🦃',
      '🕊️',
      '🐇',
      '🐁',
      '🐀',
      '🐿️',
      '🦔',
      '🌸',
      '🌺',
      '🌻',
      '🌷',
      '🌹',
      '🥀',
      '🌾',
      '🌿',
      '☘️',
      '🍀',
      '🍁',
      '🍂',
      '🍃',
      '🌍',
      '🌎',
      '🌏',
      '🌕',
      '🌖',
      '🌗',
      '🌘',
      '🌑',
      '🌒',
      '🌓',
      '🌔',
      '☀️',
      '🌤️',
      '⛅',
      '🌥️',
      '☁️',
      '🌦️',
      '🌧️',
      '⛈️',
      '🌩️',
      '🌨️',
      '❄️',
      '☃️',
      '⛄',
      '🌬️',
      '💨',
      '🌊',
      '💧',
      '💦',
      '🌈',
    ],
  },
  food: {
    label: '🍔',
    emojis: [
      '🍏',
      '🍎',
      '🍐',
      '🍊',
      '🍋',
      '🍌',
      '🍉',
      '🍇',
      '🍓',
      '🫐',
      '🍈',
      '🍒',
      '🍑',
      '🥭',
      '🍍',
      '🥥',
      '🥝',
      '🍅',
      '🍆',
      '🥑',
      '🥦',
      '🥬',
      '🥒',
      '🌶️',
      '🫑',
      '🌽',
      '🥕',
      '🫒',
      '🧄',
      '🧅',
      '🥔',
      '🍠',
      '🥐',
      '🥯',
      '🍞',
      '🥖',
      '🥨',
      '🧀',
      '🥚',
      '🍳',
      '🧈',
      '🥞',
      '🧇',
      '🥓',
      '🥩',
      '🍗',
      '🍖',
      '🌭',
      '🍔',
      '🍟',
      '🍕',
      '🥪',
      '🥙',
      '🧆',
      '🌮',
      '🌯',
      '🫔',
      '🥗',
      '🥘',
      '🫕',
      '🥫',
      '🍝',
      '🍜',
      '🍲',
      '🍛',
      '🍣',
      '🍱',
      '🥟',
      '🦪',
      '🍤',
      '🍙',
      '🍚',
      '🍘',
      '🍥',
      '🥠',
      '🥮',
      '🍢',
      '🍡',
      '🍧',
      '🍨',
      '🍦',
      '🥧',
      '🧁',
      '🍰',
      '🎂',
      '🍮',
      '🍭',
      '🍬',
      '🍫',
      '🍿',
      '🍩',
      '🍪',
      '🌰',
      '🥜',
      '🍯',
      '🥛',
      '🍼',
      '☕',
      '🫖',
      '🍵',
      '🧃',
      '🥤',
      '🧋',
      '🍶',
      '🍺',
      '🍻',
      '🥂',
      '🍷',
      '🥃',
      '🍸',
      '🍹',
      '🧉',
      '🍾',
      '🧊',
    ],
  },
  activities: {
    label: '⚽',
    emojis: [
      '⚽',
      '🏀',
      '🏈',
      '⚾',
      '🥎',
      '🎾',
      '🏐',
      '🏉',
      '🥏',
      '🎱',
      '🪀',
      '🏓',
      '🏸',
      '🏒',
      '🏑',
      '🥍',
      '🏏',
      '🪃',
      '🥅',
      '⛳',
      '🪁',
      '🏹',
      '🎣',
      '🤿',
      '🥊',
      '🥋',
      '🎽',
      '🛹',
      '🛼',
      '🛷',
      '⛸️',
      '🥌',
      '🎿',
      '⛷️',
      '🏂',
      '🪂',
      '🏋️',
      '🤸',
      '🤺',
      '🤾',
      '🏌️',
      '🏇',
      '🧘',
      '🏄',
      '🏊',
      '🤽',
      '🚣',
      '🧗',
      '🚵',
      '🚴',
      '🏆',
      '🥇',
      '🥈',
      '🥉',
      '🏅',
      '🎖️',
      '🏵️',
      '🎗️',
      '🎫',
      '🎟️',
      '🎪',
      '🤹',
      '🎭',
      '🩰',
      '🎨',
      '🎬',
      '🎤',
      '🎧',
      '🎼',
      '🎹',
      '🥁',
      '🪘',
      '🎷',
      '🎺',
      '🪗',
      '🎸',
      '🪕',
      '🎻',
      '🎲',
      '♟️',
      '🎯',
      '🎳',
      '🎮',
      '🎰',
      '🧩',
    ],
  },
  travel: {
    label: '✈️',
    emojis: [
      '🚗',
      '🚕',
      '🚙',
      '🚌',
      '🚎',
      '🏎️',
      '🚓',
      '🚑',
      '🚒',
      '🚐',
      '🛻',
      '🚚',
      '🚛',
      '🚜',
      '🛵',
      '🏍️',
      '🛺',
      '🚲',
      '🛴',
      '🚨',
      '🚔',
      '🚍',
      '🚘',
      '🚖',
      '🚡',
      '🚠',
      '🚟',
      '🚃',
      '🚋',
      '🚞',
      '🚝',
      '🚄',
      '🚅',
      '🚈',
      '🚂',
      '🚆',
      '🚇',
      '🚊',
      '🚉',
      '✈️',
      '🛫',
      '🛬',
      '🛩️',
      '💺',
      '🛰️',
      '🚀',
      '🛸',
      '🚁',
      '🛶',
      '⛵',
      '🚤',
      '🛥️',
      '🛳️',
      '⛴️',
      '🚢',
      '⚓',
      '⛽',
      '🚧',
      '🚦',
      '🚥',
      '🗺️',
      '🗿',
      '🗽',
      '🗼',
      '🏰',
      '🏯',
      '🏟️',
      '🎡',
      '🎢',
      '🎠',
      '⛲',
      '⛱️',
      '🏖️',
      '🏝️',
      '🏜️',
      '🌋',
      '⛰️',
      '🏔️',
      '🗻',
      '🏕️',
      '⛺',
      '🏠',
      '🏡',
      '🏘️',
      '🏚️',
      '🏗️',
      '🏭',
      '🏢',
      '🏬',
      '🏣',
      '🏤',
      '🏥',
      '🏦',
      '🏨',
      '🏪',
      '🏫',
      '🏩',
      '💒',
      '🏛️',
      '⛪',
      '🕌',
      '🛕',
      '🕍',
      '🕋',
      '⛩️',
      '🌅',
      '🌄',
      '🌠',
      '🌌',
      '🌉',
      '🌇',
      '🌆',
      '🏙️',
      '🌃',
      '🌁',
    ],
  },
  objects: {
    label: '🎉',
    emojis: [
      '🎉',
      '🎊',
      '🎁',
      '🎈',
      '🏆',
      '🥇',
      '🥈',
      '🥉',
      '⭐',
      '🌟',
      '✨',
      '💫',
      '🔥',
      '💯',
      '💢',
      '💥',
      '💦',
      '💨',
      '🕐',
      '⏰',
      '📅',
      '📌',
      '📍',
      '✅',
      '❌',
      '❓',
      '❗',
      '💡',
      '🔔',
      '📣',
      '📢',
      '🔊',
      '🎂',
      '🎀',
      '🪅',
      '🪄',
      '🧨',
      '🎃',
      '🎄',
      '🧧',
      '🎇',
      '🎆',
      '🧿',
      '🪬',
      '🕯️',
      '💎',
      '⚱️',
      '🏺',
      '🛍️',
      '🛒',
      '🎒',
      '👑',
      '⛑️',
      '🎓',
      '🧢',
      '🎩',
      '👒',
      '🕶️',
      '👓',
      '💄',
      '💍',
      '💼',
    ],
  },
  work: {
    label: '💼',
    emojis: [
      '💼',
      '📁',
      '📂',
      '🗂️',
      '📊',
      '📈',
      '📉',
      '📋',
      '📝',
      '✏️',
      '🖊️',
      '🖋️',
      '✒️',
      '🖌️',
      '🖍️',
      '📎',
      '🖇️',
      '🔗',
      '📌',
      '📍',
      '📬',
      '📭',
      '📮',
      '📪',
      '📫',
      '📧',
      '💻',
      '🖥️',
      '⌨️',
      '🖱️',
      '🖨️',
      '💾',
      '💿',
      '📀',
      '💽',
      '📱',
      '☎️',
      '📞',
      '📟',
      '📠',
      '🔧',
      '🔨',
      '🛠️',
      '⚙️',
      '🔩',
      '🔑',
      '🗝️',
      '🔒',
      '🔓',
      '📦',
      '🏷️',
      '📃',
      '📄',
      '📑',
      '📇',
      '📆',
      '🗓️',
      '📕',
      '📗',
      '📘',
      '📙',
      '📚',
      '📖',
    ],
  },
  symbols: {
    label: '🔣',
    emojis: [
      '✅',
      '❌',
      '❎',
      '✔️',
      '☑️',
      '❇️',
      '✳️',
      '❄️',
      '💠',
      '🔱',
      '🌀',
      '💤',
      '🚫',
      '⛔',
      '📛',
      '💯',
      '💢',
      '♨️',
      '🚷',
      '🚯',
      '🚳',
      '🚱',
      '🔞',
      '📵',
      '⚠️',
      '☢️',
      '☣️',
      '⬆️',
      '⬇️',
      '⬅️',
      '➡️',
      '↗️',
      '↘️',
      '↙️',
      '↖️',
      '↕️',
      '↔️',
      '🔃',
      '🔄',
      '↩️',
      '↪️',
      '🔁',
      '🔂',
      '🔀',
      '▶️',
      '⏩',
      '⏭️',
      '⏯️',
      '◀️',
      '⏪',
      '⏮️',
      '🔼',
      '🔽',
      '⏸️',
      '⏹️',
      '⏺️',
      '⏏️',
      '🎦',
      '🔅',
      '🔆',
      '📶',
      '📳',
      '📴',
      '#️⃣',
      '*️⃣',
      '0️⃣',
      '1️⃣',
      '2️⃣',
      '3️⃣',
      '4️⃣',
      '5️⃣',
      '6️⃣',
      '7️⃣',
      '8️⃣',
      '9️⃣',
      '🔟',
      '🔤',
      '🔡',
      '🔠',
      '🆗',
      '🆕',
      '🆙',
      '🆒',
      '🆓',
      '🆖',
      '🆚',
      '🈁',
      '💹',
      '➕',
      '➖',
      '➗',
      '✖️',
      '♾️',
      '💲',
      '💱',
      '™️',
      '©️',
      '®️',
      '〰️',
      '➰',
      '➿',
      '🔚',
      '🔙',
      '🔛',
      '🔝',
      '🔜',
      '☑️',
      '🔘',
      '⚪',
      '⚫',
      '🔴',
      '🟠',
      '🟡',
      '🟢',
      '🔵',
      '🟣',
      '🟤',
      '🔺',
      '🔻',
      '🔸',
      '🔹',
      '🔶',
      '🔷',
      '🔳',
      '🔲',
      '▪️',
      '▫️',
      '◾',
      '◽',
      '◼️',
      '◻️',
      '🟥',
      '🟧',
      '🟨',
      '🟩',
      '🟦',
      '🟪',
      '🟫',
    ],
  },
  flags: {
    label: '🏳️',
    emojis: [
      '🏳️',
      '🏴',
      '🏁',
      '🚩',
      '🏳️‍🌈',
      '🏳️‍⚧️',
      '🏴‍☠️',
      '🇫🇷',
      '🇨🇦',
      '🇧🇪',
      '🇨🇭',
      '🇱🇺',
      '🇬🇧',
      '🇺🇸',
      '🇩🇪',
      '🇪🇸',
      '🇮🇹',
      '🇵🇹',
      '🇳🇱',
      '🇮🇪',
      '🇸🇪',
      '🇳🇴',
      '🇩🇰',
      '🇫🇮',
      '🇮🇸',
      '🇵🇱',
      '🇦🇹',
      '🇬🇷',
      '🇹🇷',
      '🇷🇺',
      '🇺🇦',
      '🇨🇳',
      '🇯🇵',
      '🇰🇷',
      '🇮🇳',
      '🇧🇷',
      '🇦🇷',
      '🇲🇽',
      '🇦🇺',
      '🇳🇿',
      '🇿🇦',
      '🇲🇦',
      '🇩🇿',
      '🇹🇳',
      '🇪🇬',
      '🇸🇳',
      '🇨🇮',
    ],
  },
}

// Emoji keywords mapping for search
const EMOJI_KEYWORDS: Record<string, string[]> = {
  // Smileys
  '😀': ['sourire', 'smile', 'happy', 'heureux', 'content'],
  '😃': ['sourire', 'smile', 'happy', 'heureux', 'yeux'],
  '😄': ['rire', 'laugh', 'happy', 'content', 'joie'],
  '😁': ['sourire', 'smile', 'dents', 'heureux'],
  '😅': ['sueur', 'sweat', 'nerveux', 'ouf', 'soulage'],
  '😂': ['rire', 'laugh', 'larmes', 'mdr', 'lol', 'drole'],
  '🤣': ['rire', 'ptdr', 'mort', 'drole', 'lol'],
  '😊': ['sourire', 'timide', 'content', 'mignon'],
  '😇': ['ange', 'angel', 'innocent', 'aureole'],
  '😉': ['clin', 'wink', 'complicite'],
  '😍': ['amour', 'love', 'coeur', 'yeux', 'adore'],
  '🥰': ['amour', 'love', 'coeur', 'affection'],
  '😘': ['bisou', 'kiss', 'amour'],
  '😋': ['miam', 'yum', 'delicieux', 'langue'],
  '😛': ['langue', 'taquiner', 'blague'],
  '😜': ['clin', 'langue', 'fou', 'blague'],
  '🤪': ['fou', 'crazy', 'dingue', 'bizarre'],
  '🤔': ['reflexion', 'penser', 'hmm', 'question', 'doute'],
  '🤭': ['oups', 'secret', 'rire', 'cache'],
  '🤫': ['chut', 'secret', 'silence', 'shhh'],
  '😏': ['malicieux', 'smirk', 'confiant'],
  '😒': ['ennui', 'bof', 'sceptique'],
  '🙄': ['yeux', 'pfff', 'agace', 'enerve'],
  '😴': ['dodo', 'dormir', 'sleep', 'fatigue'],
  '🤒': ['malade', 'sick', 'fievre'],
  '🤕': ['blesse', 'hurt', 'bobo'],
  '🤢': ['malade', 'sick', 'nausee', 'degout'],

  // Gestures
  '👍': ['ok', 'bien', 'super', 'pouce', 'top', 'approve', 'oui'],
  '👎': ['non', 'mauvais', 'pas bien', 'pouce bas'],
  '👋': ['salut', 'hello', 'coucou', 'bye', 'wave'],
  '👏': ['bravo', 'applaudissement', 'clap', 'felicitations'],
  '🙌': ['celebration', 'victoire', 'yeah', 'hourra'],
  '🙏': ['merci', 'thanks', 'priere', 'svp', 'please'],
  '🤝': ['accord', 'deal', 'poignee', 'partenariat'],
  '✌️': ['paix', 'peace', 'victoire', 'deux'],
  '🤞': ['chance', 'luck', 'croiser', 'espoir'],
  '👌': ['ok', 'parfait', 'nice', 'bien'],
  '✊': ['force', 'power', 'poing', 'courage'],
  '💪': ['force', 'muscle', 'strong', 'courage'],

  // Hearts
  '❤️': ['coeur', 'heart', 'amour', 'love', 'rouge'],
  '🧡': ['coeur', 'orange', 'amour'],
  '💛': ['coeur', 'jaune', 'amour', 'amitie'],
  '💚': ['coeur', 'vert', 'nature', 'jalousie'],
  '💙': ['coeur', 'bleu', 'confiance'],
  '💜': ['coeur', 'violet', 'purple'],
  '🖤': ['coeur', 'noir', 'dark'],
  '💔': ['coeur', 'brise', 'broken', 'triste'],
  '💕': ['coeurs', 'amour', 'affection'],

  // Objects & Symbols
  '🎉': ['fete', 'party', 'celebration', 'tada', 'bravo'],
  '🎊': ['confetti', 'fete', 'celebration'],
  '🎁': ['cadeau', 'gift', 'present', 'surprise'],
  '🏆': ['trophee', 'trophy', 'victoire', 'gagner', 'champion'],
  '🥇': ['or', 'gold', 'premier', 'medaille', 'gagner'],
  '⭐': ['etoile', 'star', 'favori', 'super'],
  '✨': ['brillant', 'sparkle', 'magie', 'nouveau'],
  '🔥': ['feu', 'fire', 'hot', 'chaud', 'populaire', 'tendance'],
  '💯': ['parfait', 'perfect', 'cent', 'score', 'top'],
  '✅': ['valide', 'check', 'ok', 'fait', 'done', 'oui'],
  '❌': ['non', 'faux', 'erreur', 'annuler', 'x'],
  '❓': ['question', 'quoi', 'pourquoi'],
  '❗': ['attention', 'important', 'exclamation'],
  '💡': ['idee', 'idea', 'ampoule', 'lumiere'],
  '🔔': ['notif', 'alert', 'cloche', 'notification'],

  // Work
  '💼': ['travail', 'work', 'business', 'bureau'],
  '📁': ['dossier', 'folder', 'fichier'],
  '📊': ['graph', 'stats', 'statistiques', 'data'],
  '📈': ['hausse', 'up', 'croissance', 'progres'],
  '📉': ['baisse', 'down', 'chute'],
  '📋': ['liste', 'checklist', 'presse-papier'],
  '📝': ['note', 'memo', 'ecrire', 'rediger'],
  '💻': ['ordinateur', 'computer', 'laptop', 'pc'],
  '📧': ['email', 'mail', 'message'],
  '📞': ['telephone', 'phone', 'appel', 'call'],
  '⚙️': ['parametres', 'settings', 'config'],
  '🔑': ['cle', 'key', 'acces', 'mot de passe'],
  '🔒': ['verrou', 'lock', 'securite', 'prive'],
  '📦': ['colis', 'package', 'livraison', 'box'],
}

export function ReactionPicker({ onSelect }: ReactionPickerProps) {
  const [search, setSearch] = useState('')
  const [activeTab, setActiveTab] = useState('recent')

  const handleSelect = (emoji: string) => {
    onSelect(emoji)
    setSearch('')
  }

  // Filter emojis by search with keywords
  const filteredEmojis = useMemo(() => {
    if (!search.trim()) return []

    const searchLower = search.toLowerCase().trim()
    const allEmojis = Object.values(EMOJI_CATEGORIES).flatMap((c) => c.emojis)
    const uniqueEmojis = [...new Set(allEmojis)]

    return uniqueEmojis.filter((emoji) => {
      if (emoji.includes(searchLower)) return true
      const keywords = EMOJI_KEYWORDS[emoji] || []
      return keywords.some((kw) => kw.includes(searchLower) || searchLower.includes(kw))
    })
  }, [search])

  return (
    <div className="w-72 p-2">
      {/* Search */}
      <Input
        placeholder="Rechercher un emoji..."
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        className="mb-2 h-8 text-sm"
        aria-label="Rechercher un emoji"
      />

      {search ? (
        // Search results
        <div className="grid grid-cols-8 gap-1 max-h-48 overflow-y-auto p-1">
          {filteredEmojis.length > 0 ? (
            filteredEmojis.map((emoji) => (
              <button
                key={emoji}
                onClick={() => handleSelect(emoji)}
                className="p-1.5 text-lg hover:bg-accent rounded transition-colors"
                aria-label={`Sélectionner ${emoji}`}
              >
                {emoji}
              </button>
            ))
          ) : (
            <p className="col-span-8 text-center text-sm text-muted-foreground py-4">
              Aucun emoji trouvé pour "{search}"
            </p>
          )}
        </div>
      ) : (
        // Categories
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="w-full h-9 flex overflow-x-auto no-scrollbar mb-2 gap-0.5 justify-start">
            {Object.entries(EMOJI_CATEGORIES).map(([key, { label }]) => (
              <TabsTrigger
                key={key}
                value={key}
                className="text-base px-2 py-0.5 shrink-0 min-w-[32px]"
                aria-label={`Catégorie ${key}`}
              >
                {label}
              </TabsTrigger>
            ))}
          </TabsList>

          {Object.entries(EMOJI_CATEGORIES).map(([key, { emojis }]) => (
            <TabsContent key={key} value={key} className="mt-0">
              <div className="grid grid-cols-8 gap-1 max-h-48 overflow-y-auto p-1">
                {emojis.map((emoji) => (
                  <button
                    key={emoji}
                    onClick={() => handleSelect(emoji)}
                    className={cn(
                      'p-1.5 text-lg rounded transition-all duration-100',
                      'hover:bg-accent hover:scale-110'
                    )}
                    aria-label={`Sélectionner ${emoji}`}
                  >
                    {emoji}
                  </button>
                ))}
              </div>
            </TabsContent>
          ))}
        </Tabs>
      )}

      {/* Quick reactions bar */}
      <div className="border-t mt-2 pt-2 flex justify-center gap-1">
        {EMOJI_CATEGORIES.recent.emojis.slice(0, 6).map((emoji) => (
          <button
            key={emoji}
            onClick={() => handleSelect(emoji)}
            className={cn(
              'p-1.5 text-lg rounded-full transition-all duration-100',
              'hover:bg-primary/10 hover:scale-125'
            )}
            aria-label={`Réaction rapide ${emoji}`}
          >
            {emoji}
          </button>
        ))}
      </div>
    </div>
  )
}
