import React from 'react';
import { render, renderHook, act } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { SkeletonCard, SkeletonCardList } from './skeleton-card';

const {
  mockCard,
  mockCardHeader,
  mockCardContent,
  mockSkeleton,
  mockCn
} = vi.hoisted(() => {
  const mockCard = vi.fn(function MockCard(props: any) {
    const { children, ...rest } = props;
    return React.createElement('div', { 'data-testid': 'card', ...rest }, children);
  });
  const mockCardHeader = vi.fn(function MockCardHeader(props: any) {
    const { children, ...rest } = props;
    return React.createElement('header', { 'data-testid': 'card-header', ...rest }, children);
  });
  const mockCardContent = vi.fn(function MockCardContent(props: any) {
    const { children, ...rest } = props;
    return React.createElement('div', { 'data-testid': 'card-content', ...rest }, children);
  });
  const mockSkeleton = vi.fn(function MockSkeleton(props: any) {
    const { className, ...rest } = props;
    return React.createElement('span', { 'data-testid': 'skeleton', 'data-class': className, ...rest });
  });
  const mockCn = vi.fn((...parts: Array<string | false | undefined>) => parts.filter(Boolean).join(' '));
  return { mockCard, mockCardHeader, mockCardContent, mockSkeleton, mockCn };
});

vi.mock('@/components/ui/card', () => ({
  Card: mockCard,
  CardHeader: mockCardHeader,
  CardContent: mockCardContent
}));

vi.mock('@/components/ui/skeleton', () => ({
  Skeleton: mockSkeleton
}));

vi.mock('@/lib/utils', () => ({
  cn: mockCn
}));

describe('SkeletonCard / SkeletonCardList', () => {
  const qc = new QueryClient({
    defaultOptions: {
      queries: { retry: 0, gcTime: 0 },
      mutations: { retry: 0 }
    }
  });

  const Wrapper = ({ children }: { children?: React.ReactNode }) => (
    <QueryClientProvider client={qc}>{children}</QueryClientProvider>
  );

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders default SkeletonCard with header and 3 rows (total 8 skeletons) and uses cn to combine classes', () => {
    const { result } = renderHook(
      () => ({ jsx: <SkeletonCard /> }),
      { wrapper: Wrapper as any }
    );

    const { getAllByTestId } = render(result.current.jsx);

    // cn should have been called to combine 'overflow-hidden' and undefined
    expect(mockCn).toHaveBeenCalled();
    expect(mockCn.mock.calls[0][0]).toBe('overflow-hidden');

    // Card component received the combined className generated by cn
    expect(mockCard.mock.calls.length).toBeGreaterThan(0);
    const cardProps = mockCard.mock.calls[mockCard.mock.calls.length - 1][0];
    expect(cardProps).toHaveProperty('className');
    expect(typeof cardProps.className).toBe('string');
    expect(cardProps.className).toContain('overflow-hidden');

    // There should be 2 header skeletons + 3 rows * 2 skeletons = 8 skeleton elements
    const skeletons = getAllByTestId('skeleton');
    expect(skeletons.length).toBe(8);

    // CardHeader and CardContent should have been rendered
    expect(mockCardHeader).toHaveBeenCalled();
    expect(mockCardContent).toHaveBeenCalled();
  });

  it('omits header when hasHeader is false and respects rows and custom className', () => {
    const props = { hasHeader: false, rows: 2, className: 'custom-class' };
    const { result } = renderHook(
      () => ({ jsx: <SkeletonCard {...props} /> }),
      { wrapper: Wrapper as any }
    );

    const { getAllByTestId } = render(result.current.jsx);

    // cn should have been called with overflow-hidden and the provided class
    expect(mockCn).toHaveBeenCalled();
    // second argument should be the custom class
    const cnArgs = mockCn.mock.calls[0];
    expect(cnArgs[0]).toBe('overflow-hidden');
    expect(cnArgs[1]).toBe('custom-class');

    // Card should receive the combined className string
    const cardCall = mockCard.mock.calls[mockCard.mock.calls.length - 1][0];
    expect(cardCall.className).toContain('overflow-hidden');
    expect(cardCall.className).toContain('custom-class');

    // No CardHeader should be rendered
    expect(mockCardHeader).not.toHaveBeenCalled();

    // There should be rows * 2 skeletons = 4
    const skeletons = getAllByTestId('skeleton');
    expect(skeletons.length).toBe(4);
  });

  it('renders a list of SkeletonCard instances for SkeletonCardList with correct aggregated skeleton count', () => {
    const count = 4;
    const { result } = renderHook(
      () => ({ jsx: <SkeletonCardList count={count} /> }),
      { wrapper: Wrapper as any }
    );

    const { getAllByTestId } = render(result.current.jsx);

    // Each SkeletonCard defaults to header (2) + 3 rows *2 = 8 skeletons
    const expectedPerCard = 8;
    const expectedTotal = count * expectedPerCard;

    const skeletons = getAllByTestId('skeleton');
    expect(skeletons.length).toBe(expectedTotal);

    // Card should have been called exactly `count` times
    // Note: mockCard is called once per card rendered
    expect(mockCard.mock.calls.length).toBe(count);
  });
});